package co.edu.usc.interacciones.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Drugbank implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drugbank.id
     *
     * @mbggenerated
     */
    private BigDecimal id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drugbank.drugbank_id
     *
     * @mbggenerated
     */
    private String drugbankId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drugbank.atc
     *
     * @mbggenerated
     */
    private String atc;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drugbank.interaccion
     *
     * @mbggenerated
     */
    private String interaccion;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drugbank.descripcion
     *
     * @mbggenerated
     */
    private String descripcion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drugbank.id
     *
     * @return the value of drugbank.id
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drugbank.id
     *
     * @param id the value for drugbank.id
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drugbank.drugbank_id
     *
     * @return the value of drugbank.drugbank_id
     * @mbggenerated
     */
    public String getDrugbankId() {
        return drugbankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drugbank.drugbank_id
     *
     * @param drugbankId the value for drugbank.drugbank_id
     * @mbggenerated
     */
    public void setDrugbankId(String drugbankId) {
        this.drugbankId = drugbankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drugbank.atc
     *
     * @return the value of drugbank.atc
     * @mbggenerated
     */
    public String getAtc() {
        return atc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drugbank.atc
     *
     * @param atc the value for drugbank.atc
     * @mbggenerated
     */
    public void setAtc(String atc) {
        this.atc = atc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drugbank.interaccion
     *
     * @return the value of drugbank.interaccion
     * @mbggenerated
     */
    public String getInteraccion() {
        return interaccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drugbank.interaccion
     *
     * @param interaccion the value for drugbank.interaccion
     * @mbggenerated
     */
    public void setInteraccion(String interaccion) {
        this.interaccion = interaccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drugbank.descripcion
     *
     * @return the value of drugbank.descripcion
     * @mbggenerated
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drugbank.descripcion
     *
     * @param descripcion the value for drugbank.descripcion
     * @mbggenerated
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Drugbank other = (Drugbank) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getDrugbankId() == null ? other.getDrugbankId() == null : this.getDrugbankId().equals(other.getDrugbankId()))
                && (this.getAtc() == null ? other.getAtc() == null : this.getAtc().equals(other.getAtc()))
                && (this.getInteraccion() == null ? other.getInteraccion() == null : this.getInteraccion().equals(other.getInteraccion()))
                && (this.getDescripcion() == null ? other.getDescripcion() == null : this.getDescripcion().equals(other.getDescripcion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDrugbankId() == null) ? 0 : getDrugbankId().hashCode());
        result = prime * result + ((getAtc() == null) ? 0 : getAtc().hashCode());
        result = prime * result + ((getInteraccion() == null) ? 0 : getInteraccion().hashCode());
        result = prime * result + ((getDescripcion() == null) ? 0 : getDescripcion().hashCode());
        return result;
    }
}