package co.edu.usc.interacciones.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DrugbankExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    public DrugbankExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdIsNull() {
            addCriterion("drugbank_id is null");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdIsNotNull() {
            addCriterion("drugbank_id is not null");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdEqualTo(String value) {
            addCriterion("drugbank_id =", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdNotEqualTo(String value) {
            addCriterion("drugbank_id <>", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdGreaterThan(String value) {
            addCriterion("drugbank_id >", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdGreaterThanOrEqualTo(String value) {
            addCriterion("drugbank_id >=", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdLessThan(String value) {
            addCriterion("drugbank_id <", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdLessThanOrEqualTo(String value) {
            addCriterion("drugbank_id <=", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdLike(String value) {
            addCriterion("drugbank_id like", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdNotLike(String value) {
            addCriterion("drugbank_id not like", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdIn(List<String> values) {
            addCriterion("drugbank_id in", values, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdNotIn(List<String> values) {
            addCriterion("drugbank_id not in", values, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdBetween(String value1, String value2) {
            addCriterion("drugbank_id between", value1, value2, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdNotBetween(String value1, String value2) {
            addCriterion("drugbank_id not between", value1, value2, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andAtcIsNull() {
            addCriterion("atc is null");
            return (Criteria) this;
        }

        public Criteria andAtcIsNotNull() {
            addCriterion("atc is not null");
            return (Criteria) this;
        }

        public Criteria andAtcEqualTo(String value) {
            addCriterion("atc =", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcNotEqualTo(String value) {
            addCriterion("atc <>", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcGreaterThan(String value) {
            addCriterion("atc >", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcGreaterThanOrEqualTo(String value) {
            addCriterion("atc >=", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcLessThan(String value) {
            addCriterion("atc <", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcLessThanOrEqualTo(String value) {
            addCriterion("atc <=", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcLike(String value) {
            addCriterion("atc like", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcNotLike(String value) {
            addCriterion("atc not like", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcIn(List<String> values) {
            addCriterion("atc in", values, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcNotIn(List<String> values) {
            addCriterion("atc not in", values, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcBetween(String value1, String value2) {
            addCriterion("atc between", value1, value2, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcNotBetween(String value1, String value2) {
            addCriterion("atc not between", value1, value2, "atc");
            return (Criteria) this;
        }

        public Criteria andInteraccionIsNull() {
            addCriterion("interaccion is null");
            return (Criteria) this;
        }

        public Criteria andInteraccionIsNotNull() {
            addCriterion("interaccion is not null");
            return (Criteria) this;
        }

        public Criteria andInteraccionEqualTo(String value) {
            addCriterion("interaccion =", value, "interaccion");
            return (Criteria) this;
        }

        public Criteria andInteraccionNotEqualTo(String value) {
            addCriterion("interaccion <>", value, "interaccion");
            return (Criteria) this;
        }

        public Criteria andInteraccionGreaterThan(String value) {
            addCriterion("interaccion >", value, "interaccion");
            return (Criteria) this;
        }

        public Criteria andInteraccionGreaterThanOrEqualTo(String value) {
            addCriterion("interaccion >=", value, "interaccion");
            return (Criteria) this;
        }

        public Criteria andInteraccionLessThan(String value) {
            addCriterion("interaccion <", value, "interaccion");
            return (Criteria) this;
        }

        public Criteria andInteraccionLessThanOrEqualTo(String value) {
            addCriterion("interaccion <=", value, "interaccion");
            return (Criteria) this;
        }

        public Criteria andInteraccionLike(String value) {
            addCriterion("interaccion like", value, "interaccion");
            return (Criteria) this;
        }

        public Criteria andInteraccionNotLike(String value) {
            addCriterion("interaccion not like", value, "interaccion");
            return (Criteria) this;
        }

        public Criteria andInteraccionIn(List<String> values) {
            addCriterion("interaccion in", values, "interaccion");
            return (Criteria) this;
        }

        public Criteria andInteraccionNotIn(List<String> values) {
            addCriterion("interaccion not in", values, "interaccion");
            return (Criteria) this;
        }

        public Criteria andInteraccionBetween(String value1, String value2) {
            addCriterion("interaccion between", value1, value2, "interaccion");
            return (Criteria) this;
        }

        public Criteria andInteraccionNotBetween(String value1, String value2) {
            addCriterion("interaccion not between", value1, value2, "interaccion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("descripcion is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("descripcion is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("descripcion =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("descripcion <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("descripcion >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("descripcion <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("descripcion <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("descripcion like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("descripcion not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("descripcion in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("descripcion not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("descripcion between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("descripcion not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdLikeInsensitive(String value) {
            addCriterion("upper(drugbank_id) like", value.toUpperCase(), "drugbankId");
            return (Criteria) this;
        }

        public Criteria andAtcLikeInsensitive(String value) {
            addCriterion("upper(atc) like", value.toUpperCase(), "atc");
            return (Criteria) this;
        }

        public Criteria andInteraccionLikeInsensitive(String value) {
            addCriterion("upper(interaccion) like", value.toUpperCase(), "interaccion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLikeInsensitive(String value) {
            addCriterion("upper(descripcion) like", value.toUpperCase(), "descripcion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drugbank
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drugbank
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}