package co.edu.usc.interacciones.dao.model;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EfectosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efectos
     *
     * @mbggenerated
     */
    int countByExample(EfectosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efectos
     *
     * @mbggenerated
     */
    int deleteByExample(EfectosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efectos
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short idefectos);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efectos
     *
     * @mbggenerated
     */
    int insert(Efectos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efectos
     *
     * @mbggenerated
     */
    int insertSelective(Efectos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efectos
     *
     * @mbggenerated
     */
    List<Efectos> selectByExample(EfectosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efectos
     *
     * @mbggenerated
     */
    Efectos selectByPrimaryKey(Short idefectos);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efectos
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Efectos record, @Param("example") EfectosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efectos
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Efectos record, @Param("example") EfectosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efectos
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Efectos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efectos
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Efectos record);
}