package co.edu.usc.interacciones.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class FabricImport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usc.fabric_import
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usc.fabric_import.idfabric_import
     *
     * @mbggenerated
     */
    private BigDecimal idfabricImport;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usc.fabric_import.nombre
     *
     * @mbggenerated
     */
    private String nombre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usc.fabric_import.idfabric_import
     *
     * @return the value of usc.fabric_import.idfabric_import
     * @mbggenerated
     */
    public BigDecimal getIdfabricImport() {
        return idfabricImport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usc.fabric_import.idfabric_import
     *
     * @param idfabricImport the value for usc.fabric_import.idfabric_import
     * @mbggenerated
     */
    public void setIdfabricImport(BigDecimal idfabricImport) {
        this.idfabricImport = idfabricImport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usc.fabric_import.nombre
     *
     * @return the value of usc.fabric_import.nombre
     * @mbggenerated
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usc.fabric_import.nombre
     *
     * @param nombre the value for usc.fabric_import.nombre
     * @mbggenerated
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.fabric_import
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FabricImport other = (FabricImport) that;
        return (this.getIdfabricImport() == null ? other.getIdfabricImport() == null : this.getIdfabricImport().equals(other.getIdfabricImport()))
                && (this.getNombre() == null ? other.getNombre() == null : this.getNombre().equals(other.getNombre()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.fabric_import
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdfabricImport() == null) ? 0 : getIdfabricImport().hashCode());
        result = prime * result + ((getNombre() == null) ? 0 : getNombre().hashCode());
        return result;
    }
}