package co.edu.usc.interacciones.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Interaccionescomponentes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usc.interaccionescomponentes.componentea
     *
     * @mbggenerated
     */
    private String componentea;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usc.interaccionescomponentes.componenteb
     *
     * @mbggenerated
     */
    private String componenteb;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usc.interaccionescomponentes.descripcion
     *
     * @mbggenerated
     */
    private String descripcion;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usc.interaccionescomponentes.nivel
     *
     * @mbggenerated
     */
    private BigDecimal nivel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usc.interaccionescomponentes.componentea
     *
     * @return the value of usc.interaccionescomponentes.componentea
     * @mbggenerated
     */
    public String getComponentea() {
        return componentea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usc.interaccionescomponentes.componentea
     *
     * @param componentea the value for usc.interaccionescomponentes.componentea
     * @mbggenerated
     */
    public void setComponentea(String componentea) {
        this.componentea = componentea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usc.interaccionescomponentes.componenteb
     *
     * @return the value of usc.interaccionescomponentes.componenteb
     * @mbggenerated
     */
    public String getComponenteb() {
        return componenteb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usc.interaccionescomponentes.componenteb
     *
     * @param componenteb the value for usc.interaccionescomponentes.componenteb
     * @mbggenerated
     */
    public void setComponenteb(String componenteb) {
        this.componenteb = componenteb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usc.interaccionescomponentes.descripcion
     *
     * @return the value of usc.interaccionescomponentes.descripcion
     * @mbggenerated
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usc.interaccionescomponentes.descripcion
     *
     * @param descripcion the value for usc.interaccionescomponentes.descripcion
     * @mbggenerated
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usc.interaccionescomponentes.nivel
     *
     * @return the value of usc.interaccionescomponentes.nivel
     * @mbggenerated
     */
    public BigDecimal getNivel() {
        return nivel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usc.interaccionescomponentes.nivel
     *
     * @param nivel the value for usc.interaccionescomponentes.nivel
     * @mbggenerated
     */
    public void setNivel(BigDecimal nivel) {
        this.nivel = nivel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Interaccionescomponentes other = (Interaccionescomponentes) that;
        return (this.getComponentea() == null ? other.getComponentea() == null : this.getComponentea().equals(other.getComponentea()))
                && (this.getComponenteb() == null ? other.getComponenteb() == null : this.getComponenteb().equals(other.getComponenteb()))
                && (this.getDescripcion() == null ? other.getDescripcion() == null : this.getDescripcion().equals(other.getDescripcion()))
                && (this.getNivel() == null ? other.getNivel() == null : this.getNivel().equals(other.getNivel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getComponentea() == null) ? 0 : getComponentea().hashCode());
        result = prime * result + ((getComponenteb() == null) ? 0 : getComponenteb().hashCode());
        result = prime * result + ((getDescripcion() == null) ? 0 : getDescripcion().hashCode());
        result = prime * result + ((getNivel() == null) ? 0 : getNivel().hashCode());
        return result;
    }
}