package co.edu.usc.interacciones.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class InteraccionescomponentesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    public InteraccionescomponentesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andComponenteaIsNull() {
            addCriterion("componentea is null");
            return (Criteria) this;
        }

        public Criteria andComponenteaIsNotNull() {
            addCriterion("componentea is not null");
            return (Criteria) this;
        }

        public Criteria andComponenteaEqualTo(String value) {
            addCriterion("componentea =", value, "componentea");
            return (Criteria) this;
        }

        public Criteria andComponenteaNotEqualTo(String value) {
            addCriterion("componentea <>", value, "componentea");
            return (Criteria) this;
        }

        public Criteria andComponenteaGreaterThan(String value) {
            addCriterion("componentea >", value, "componentea");
            return (Criteria) this;
        }

        public Criteria andComponenteaGreaterThanOrEqualTo(String value) {
            addCriterion("componentea >=", value, "componentea");
            return (Criteria) this;
        }

        public Criteria andComponenteaLessThan(String value) {
            addCriterion("componentea <", value, "componentea");
            return (Criteria) this;
        }

        public Criteria andComponenteaLessThanOrEqualTo(String value) {
            addCriterion("componentea <=", value, "componentea");
            return (Criteria) this;
        }

        public Criteria andComponenteaLike(String value) {
            addCriterion("componentea like", value, "componentea");
            return (Criteria) this;
        }

        public Criteria andComponenteaNotLike(String value) {
            addCriterion("componentea not like", value, "componentea");
            return (Criteria) this;
        }

        public Criteria andComponenteaIn(List<String> values) {
            addCriterion("componentea in", values, "componentea");
            return (Criteria) this;
        }

        public Criteria andComponenteaNotIn(List<String> values) {
            addCriterion("componentea not in", values, "componentea");
            return (Criteria) this;
        }

        public Criteria andComponenteaBetween(String value1, String value2) {
            addCriterion("componentea between", value1, value2, "componentea");
            return (Criteria) this;
        }

        public Criteria andComponenteaNotBetween(String value1, String value2) {
            addCriterion("componentea not between", value1, value2, "componentea");
            return (Criteria) this;
        }

        public Criteria andComponentebIsNull() {
            addCriterion("componenteb is null");
            return (Criteria) this;
        }

        public Criteria andComponentebIsNotNull() {
            addCriterion("componenteb is not null");
            return (Criteria) this;
        }

        public Criteria andComponentebEqualTo(String value) {
            addCriterion("componenteb =", value, "componenteb");
            return (Criteria) this;
        }

        public Criteria andComponentebNotEqualTo(String value) {
            addCriterion("componenteb <>", value, "componenteb");
            return (Criteria) this;
        }

        public Criteria andComponentebGreaterThan(String value) {
            addCriterion("componenteb >", value, "componenteb");
            return (Criteria) this;
        }

        public Criteria andComponentebGreaterThanOrEqualTo(String value) {
            addCriterion("componenteb >=", value, "componenteb");
            return (Criteria) this;
        }

        public Criteria andComponentebLessThan(String value) {
            addCriterion("componenteb <", value, "componenteb");
            return (Criteria) this;
        }

        public Criteria andComponentebLessThanOrEqualTo(String value) {
            addCriterion("componenteb <=", value, "componenteb");
            return (Criteria) this;
        }

        public Criteria andComponentebLike(String value) {
            addCriterion("componenteb like", value, "componenteb");
            return (Criteria) this;
        }

        public Criteria andComponentebNotLike(String value) {
            addCriterion("componenteb not like", value, "componenteb");
            return (Criteria) this;
        }

        public Criteria andComponentebIn(List<String> values) {
            addCriterion("componenteb in", values, "componenteb");
            return (Criteria) this;
        }

        public Criteria andComponentebNotIn(List<String> values) {
            addCriterion("componenteb not in", values, "componenteb");
            return (Criteria) this;
        }

        public Criteria andComponentebBetween(String value1, String value2) {
            addCriterion("componenteb between", value1, value2, "componenteb");
            return (Criteria) this;
        }

        public Criteria andComponentebNotBetween(String value1, String value2) {
            addCriterion("componenteb not between", value1, value2, "componenteb");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("descripcion is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("descripcion is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("descripcion =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("descripcion <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("descripcion >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("descripcion <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("descripcion <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("descripcion like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("descripcion not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("descripcion in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("descripcion not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("descripcion between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("descripcion not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andNivelIsNull() {
            addCriterion("nivel is null");
            return (Criteria) this;
        }

        public Criteria andNivelIsNotNull() {
            addCriterion("nivel is not null");
            return (Criteria) this;
        }

        public Criteria andNivelEqualTo(BigDecimal value) {
            addCriterion("nivel =", value, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelNotEqualTo(BigDecimal value) {
            addCriterion("nivel <>", value, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelGreaterThan(BigDecimal value) {
            addCriterion("nivel >", value, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("nivel >=", value, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelLessThan(BigDecimal value) {
            addCriterion("nivel <", value, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelLessThanOrEqualTo(BigDecimal value) {
            addCriterion("nivel <=", value, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelIn(List<BigDecimal> values) {
            addCriterion("nivel in", values, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelNotIn(List<BigDecimal> values) {
            addCriterion("nivel not in", values, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("nivel between", value1, value2, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("nivel not between", value1, value2, "nivel");
            return (Criteria) this;
        }

        public Criteria andComponenteaLikeInsensitive(String value) {
            addCriterion("upper(componentea) like", value.toUpperCase(), "componentea");
            return (Criteria) this;
        }

        public Criteria andComponentebLikeInsensitive(String value) {
            addCriterion("upper(componenteb) like", value.toUpperCase(), "componenteb");
            return (Criteria) this;
        }

        public Criteria andDescripcionLikeInsensitive(String value) {
            addCriterion("upper(descripcion) like", value.toUpperCase(), "descripcion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usc.interaccionescomponentes
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}