package co.edu.usc.interacciones.dao.model;

import co.edu.usc.interacciones.dao.model.Interacciones;
import co.edu.usc.interacciones.dao.model.InteraccionesExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InteraccionesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interacciones
     *
     * @mbggenerated
     */
    int countByExample(InteraccionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interacciones
     *
     * @mbggenerated
     */
    int deleteByExample(InteraccionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interacciones
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal idinteracciones);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interacciones
     *
     * @mbggenerated
     */
    int insert(Interacciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interacciones
     *
     * @mbggenerated
     */
    int insertSelective(Interacciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interacciones
     *
     * @mbggenerated
     */
    List<Interacciones> selectByExample(InteraccionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interacciones
     *
     * @mbggenerated
     */
    Interacciones selectByPrimaryKey(BigDecimal idinteracciones);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interacciones
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Interacciones record, @Param("example") InteraccionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interacciones
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Interacciones record, @Param("example") InteraccionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interacciones
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Interacciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interacciones
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Interacciones record);
}