package co.edu.usc.interacciones.dao.model;

import java.io.Serializable;

public class MedicamentosVigentes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.expediente
     *
     * @mbggenerated
     */
    private String expediente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.producto
     *
     * @mbggenerated
     */
    private String producto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.titular
     *
     * @mbggenerated
     */
    private String titular;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.registro_sanitario
     *
     * @mbggenerated
     */
    private String registroSanitario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.fecha_expedicion
     *
     * @mbggenerated
     */
    private String fechaExpedicion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.fecha_vencimiento
     *
     * @mbggenerated
     */
    private String fechaVencimiento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.estado_registro
     *
     * @mbggenerated
     */
    private String estadoRegistro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.expediente_cum
     *
     * @mbggenerated
     */
    private String expedienteCum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.consecutivo
     *
     * @mbggenerated
     */
    private String consecutivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.cantidad_cum
     *
     * @mbggenerated
     */
    private String cantidadCum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.descripcion_comercial
     *
     * @mbggenerated
     */
    private String descripcionComercial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.estado_cum
     *
     * @mbggenerated
     */
    private String estadoCum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.fecha_activo
     *
     * @mbggenerated
     */
    private String fechaActivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.fecha_inactivo
     *
     * @mbggenerated
     */
    private String fechaInactivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.muestra_medica
     *
     * @mbggenerated
     */
    private String muestraMedica;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.unidad
     *
     * @mbggenerated
     */
    private String unidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.atc
     *
     * @mbggenerated
     */
    private String atc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.descripcion_atc
     *
     * @mbggenerated
     */
    private String descripcionAtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.via_administracion
     *
     * @mbggenerated
     */
    private String viaAdministracion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.concentracion
     *
     * @mbggenerated
     */
    private String concentracion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.principio_activo
     *
     * @mbggenerated
     */
    private String principioActivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.unidad_medida
     *
     * @mbggenerated
     */
    private String unidadMedida;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.cantidad
     *
     * @mbggenerated
     */
    private String cantidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.unidad_referencia
     *
     * @mbggenerated
     */
    private String unidadReferencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.forma_farmaceutica
     *
     * @mbggenerated
     */
    private String formaFarmaceutica;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.nombre_rol
     *
     * @mbggenerated
     */
    private String nombreRol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.tipo_rol
     *
     * @mbggenerated
     */
    private String tipoRol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicamentos_vigentes.modalidad
     *
     * @mbggenerated
     */
    private String modalidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.expediente
     *
     * @return the value of medicamentos_vigentes.expediente
     *
     * @mbggenerated
     */
    public String getExpediente() {
        return expediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.expediente
     *
     * @param expediente the value for medicamentos_vigentes.expediente
     *
     * @mbggenerated
     */
    public void setExpediente(String expediente) {
        this.expediente = expediente == null ? null : expediente.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.producto
     *
     * @return the value of medicamentos_vigentes.producto
     *
     * @mbggenerated
     */
    public String getProducto() {
        return producto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.producto
     *
     * @param producto the value for medicamentos_vigentes.producto
     *
     * @mbggenerated
     */
    public void setProducto(String producto) {
        this.producto = producto == null ? null : producto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.titular
     *
     * @return the value of medicamentos_vigentes.titular
     *
     * @mbggenerated
     */
    public String getTitular() {
        return titular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.titular
     *
     * @param titular the value for medicamentos_vigentes.titular
     *
     * @mbggenerated
     */
    public void setTitular(String titular) {
        this.titular = titular == null ? null : titular.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.registro_sanitario
     *
     * @return the value of medicamentos_vigentes.registro_sanitario
     *
     * @mbggenerated
     */
    public String getRegistroSanitario() {
        return registroSanitario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.registro_sanitario
     *
     * @param registroSanitario the value for medicamentos_vigentes.registro_sanitario
     *
     * @mbggenerated
     */
    public void setRegistroSanitario(String registroSanitario) {
        this.registroSanitario = registroSanitario == null ? null : registroSanitario.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.fecha_expedicion
     *
     * @return the value of medicamentos_vigentes.fecha_expedicion
     *
     * @mbggenerated
     */
    public String getFechaExpedicion() {
        return fechaExpedicion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.fecha_expedicion
     *
     * @param fechaExpedicion the value for medicamentos_vigentes.fecha_expedicion
     *
     * @mbggenerated
     */
    public void setFechaExpedicion(String fechaExpedicion) {
        this.fechaExpedicion = fechaExpedicion == null ? null : fechaExpedicion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.fecha_vencimiento
     *
     * @return the value of medicamentos_vigentes.fecha_vencimiento
     *
     * @mbggenerated
     */
    public String getFechaVencimiento() {
        return fechaVencimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.fecha_vencimiento
     *
     * @param fechaVencimiento the value for medicamentos_vigentes.fecha_vencimiento
     *
     * @mbggenerated
     */
    public void setFechaVencimiento(String fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento == null ? null : fechaVencimiento.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.estado_registro
     *
     * @return the value of medicamentos_vigentes.estado_registro
     *
     * @mbggenerated
     */
    public String getEstadoRegistro() {
        return estadoRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.estado_registro
     *
     * @param estadoRegistro the value for medicamentos_vigentes.estado_registro
     *
     * @mbggenerated
     */
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro == null ? null : estadoRegistro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.expediente_cum
     *
     * @return the value of medicamentos_vigentes.expediente_cum
     *
     * @mbggenerated
     */
    public String getExpedienteCum() {
        return expedienteCum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.expediente_cum
     *
     * @param expedienteCum the value for medicamentos_vigentes.expediente_cum
     *
     * @mbggenerated
     */
    public void setExpedienteCum(String expedienteCum) {
        this.expedienteCum = expedienteCum == null ? null : expedienteCum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.consecutivo
     *
     * @return the value of medicamentos_vigentes.consecutivo
     *
     * @mbggenerated
     */
    public String getConsecutivo() {
        return consecutivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.consecutivo
     *
     * @param consecutivo the value for medicamentos_vigentes.consecutivo
     *
     * @mbggenerated
     */
    public void setConsecutivo(String consecutivo) {
        this.consecutivo = consecutivo == null ? null : consecutivo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.cantidad_cum
     *
     * @return the value of medicamentos_vigentes.cantidad_cum
     *
     * @mbggenerated
     */
    public String getCantidadCum() {
        return cantidadCum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.cantidad_cum
     *
     * @param cantidadCum the value for medicamentos_vigentes.cantidad_cum
     *
     * @mbggenerated
     */
    public void setCantidadCum(String cantidadCum) {
        this.cantidadCum = cantidadCum == null ? null : cantidadCum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.descripcion_comercial
     *
     * @return the value of medicamentos_vigentes.descripcion_comercial
     *
     * @mbggenerated
     */
    public String getDescripcionComercial() {
        return descripcionComercial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.descripcion_comercial
     *
     * @param descripcionComercial the value for medicamentos_vigentes.descripcion_comercial
     *
     * @mbggenerated
     */
    public void setDescripcionComercial(String descripcionComercial) {
        this.descripcionComercial = descripcionComercial == null ? null : descripcionComercial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.estado_cum
     *
     * @return the value of medicamentos_vigentes.estado_cum
     *
     * @mbggenerated
     */
    public String getEstadoCum() {
        return estadoCum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.estado_cum
     *
     * @param estadoCum the value for medicamentos_vigentes.estado_cum
     *
     * @mbggenerated
     */
    public void setEstadoCum(String estadoCum) {
        this.estadoCum = estadoCum == null ? null : estadoCum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.fecha_activo
     *
     * @return the value of medicamentos_vigentes.fecha_activo
     *
     * @mbggenerated
     */
    public String getFechaActivo() {
        return fechaActivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.fecha_activo
     *
     * @param fechaActivo the value for medicamentos_vigentes.fecha_activo
     *
     * @mbggenerated
     */
    public void setFechaActivo(String fechaActivo) {
        this.fechaActivo = fechaActivo == null ? null : fechaActivo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.fecha_inactivo
     *
     * @return the value of medicamentos_vigentes.fecha_inactivo
     *
     * @mbggenerated
     */
    public String getFechaInactivo() {
        return fechaInactivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.fecha_inactivo
     *
     * @param fechaInactivo the value for medicamentos_vigentes.fecha_inactivo
     *
     * @mbggenerated
     */
    public void setFechaInactivo(String fechaInactivo) {
        this.fechaInactivo = fechaInactivo == null ? null : fechaInactivo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.muestra_medica
     *
     * @return the value of medicamentos_vigentes.muestra_medica
     *
     * @mbggenerated
     */
    public String getMuestraMedica() {
        return muestraMedica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.muestra_medica
     *
     * @param muestraMedica the value for medicamentos_vigentes.muestra_medica
     *
     * @mbggenerated
     */
    public void setMuestraMedica(String muestraMedica) {
        this.muestraMedica = muestraMedica == null ? null : muestraMedica.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.unidad
     *
     * @return the value of medicamentos_vigentes.unidad
     *
     * @mbggenerated
     */
    public String getUnidad() {
        return unidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.unidad
     *
     * @param unidad the value for medicamentos_vigentes.unidad
     *
     * @mbggenerated
     */
    public void setUnidad(String unidad) {
        this.unidad = unidad == null ? null : unidad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.atc
     *
     * @return the value of medicamentos_vigentes.atc
     *
     * @mbggenerated
     */
    public String getAtc() {
        return atc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.atc
     *
     * @param atc the value for medicamentos_vigentes.atc
     *
     * @mbggenerated
     */
    public void setAtc(String atc) {
        this.atc = atc == null ? null : atc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.descripcion_atc
     *
     * @return the value of medicamentos_vigentes.descripcion_atc
     *
     * @mbggenerated
     */
    public String getDescripcionAtc() {
        return descripcionAtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.descripcion_atc
     *
     * @param descripcionAtc the value for medicamentos_vigentes.descripcion_atc
     *
     * @mbggenerated
     */
    public void setDescripcionAtc(String descripcionAtc) {
        this.descripcionAtc = descripcionAtc == null ? null : descripcionAtc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.via_administracion
     *
     * @return the value of medicamentos_vigentes.via_administracion
     *
     * @mbggenerated
     */
    public String getViaAdministracion() {
        return viaAdministracion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.via_administracion
     *
     * @param viaAdministracion the value for medicamentos_vigentes.via_administracion
     *
     * @mbggenerated
     */
    public void setViaAdministracion(String viaAdministracion) {
        this.viaAdministracion = viaAdministracion == null ? null : viaAdministracion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.concentracion
     *
     * @return the value of medicamentos_vigentes.concentracion
     *
     * @mbggenerated
     */
    public String getConcentracion() {
        return concentracion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.concentracion
     *
     * @param concentracion the value for medicamentos_vigentes.concentracion
     *
     * @mbggenerated
     */
    public void setConcentracion(String concentracion) {
        this.concentracion = concentracion == null ? null : concentracion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.principio_activo
     *
     * @return the value of medicamentos_vigentes.principio_activo
     *
     * @mbggenerated
     */
    public String getPrincipioActivo() {
        return principioActivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.principio_activo
     *
     * @param principioActivo the value for medicamentos_vigentes.principio_activo
     *
     * @mbggenerated
     */
    public void setPrincipioActivo(String principioActivo) {
        this.principioActivo = principioActivo == null ? null : principioActivo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.unidad_medida
     *
     * @return the value of medicamentos_vigentes.unidad_medida
     *
     * @mbggenerated
     */
    public String getUnidadMedida() {
        return unidadMedida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.unidad_medida
     *
     * @param unidadMedida the value for medicamentos_vigentes.unidad_medida
     *
     * @mbggenerated
     */
    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida == null ? null : unidadMedida.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.cantidad
     *
     * @return the value of medicamentos_vigentes.cantidad
     *
     * @mbggenerated
     */
    public String getCantidad() {
        return cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.cantidad
     *
     * @param cantidad the value for medicamentos_vigentes.cantidad
     *
     * @mbggenerated
     */
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad == null ? null : cantidad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.unidad_referencia
     *
     * @return the value of medicamentos_vigentes.unidad_referencia
     *
     * @mbggenerated
     */
    public String getUnidadReferencia() {
        return unidadReferencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.unidad_referencia
     *
     * @param unidadReferencia the value for medicamentos_vigentes.unidad_referencia
     *
     * @mbggenerated
     */
    public void setUnidadReferencia(String unidadReferencia) {
        this.unidadReferencia = unidadReferencia == null ? null : unidadReferencia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.forma_farmaceutica
     *
     * @return the value of medicamentos_vigentes.forma_farmaceutica
     *
     * @mbggenerated
     */
    public String getFormaFarmaceutica() {
        return formaFarmaceutica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.forma_farmaceutica
     *
     * @param formaFarmaceutica the value for medicamentos_vigentes.forma_farmaceutica
     *
     * @mbggenerated
     */
    public void setFormaFarmaceutica(String formaFarmaceutica) {
        this.formaFarmaceutica = formaFarmaceutica == null ? null : formaFarmaceutica.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.nombre_rol
     *
     * @return the value of medicamentos_vigentes.nombre_rol
     *
     * @mbggenerated
     */
    public String getNombreRol() {
        return nombreRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.nombre_rol
     *
     * @param nombreRol the value for medicamentos_vigentes.nombre_rol
     *
     * @mbggenerated
     */
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol == null ? null : nombreRol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.tipo_rol
     *
     * @return the value of medicamentos_vigentes.tipo_rol
     *
     * @mbggenerated
     */
    public String getTipoRol() {
        return tipoRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.tipo_rol
     *
     * @param tipoRol the value for medicamentos_vigentes.tipo_rol
     *
     * @mbggenerated
     */
    public void setTipoRol(String tipoRol) {
        this.tipoRol = tipoRol == null ? null : tipoRol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicamentos_vigentes.modalidad
     *
     * @return the value of medicamentos_vigentes.modalidad
     *
     * @mbggenerated
     */
    public String getModalidad() {
        return modalidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicamentos_vigentes.modalidad
     *
     * @param modalidad the value for medicamentos_vigentes.modalidad
     *
     * @mbggenerated
     */
    public void setModalidad(String modalidad) {
        this.modalidad = modalidad == null ? null : modalidad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MedicamentosVigentes other = (MedicamentosVigentes) that;
        return (this.getExpediente() == null ? other.getExpediente() == null : this.getExpediente().equals(other.getExpediente()))
            && (this.getProducto() == null ? other.getProducto() == null : this.getProducto().equals(other.getProducto()))
            && (this.getTitular() == null ? other.getTitular() == null : this.getTitular().equals(other.getTitular()))
            && (this.getRegistroSanitario() == null ? other.getRegistroSanitario() == null : this.getRegistroSanitario().equals(other.getRegistroSanitario()))
            && (this.getFechaExpedicion() == null ? other.getFechaExpedicion() == null : this.getFechaExpedicion().equals(other.getFechaExpedicion()))
            && (this.getFechaVencimiento() == null ? other.getFechaVencimiento() == null : this.getFechaVencimiento().equals(other.getFechaVencimiento()))
            && (this.getEstadoRegistro() == null ? other.getEstadoRegistro() == null : this.getEstadoRegistro().equals(other.getEstadoRegistro()))
            && (this.getExpedienteCum() == null ? other.getExpedienteCum() == null : this.getExpedienteCum().equals(other.getExpedienteCum()))
            && (this.getConsecutivo() == null ? other.getConsecutivo() == null : this.getConsecutivo().equals(other.getConsecutivo()))
            && (this.getCantidadCum() == null ? other.getCantidadCum() == null : this.getCantidadCum().equals(other.getCantidadCum()))
            && (this.getDescripcionComercial() == null ? other.getDescripcionComercial() == null : this.getDescripcionComercial().equals(other.getDescripcionComercial()))
            && (this.getEstadoCum() == null ? other.getEstadoCum() == null : this.getEstadoCum().equals(other.getEstadoCum()))
            && (this.getFechaActivo() == null ? other.getFechaActivo() == null : this.getFechaActivo().equals(other.getFechaActivo()))
            && (this.getFechaInactivo() == null ? other.getFechaInactivo() == null : this.getFechaInactivo().equals(other.getFechaInactivo()))
            && (this.getMuestraMedica() == null ? other.getMuestraMedica() == null : this.getMuestraMedica().equals(other.getMuestraMedica()))
            && (this.getUnidad() == null ? other.getUnidad() == null : this.getUnidad().equals(other.getUnidad()))
            && (this.getAtc() == null ? other.getAtc() == null : this.getAtc().equals(other.getAtc()))
            && (this.getDescripcionAtc() == null ? other.getDescripcionAtc() == null : this.getDescripcionAtc().equals(other.getDescripcionAtc()))
            && (this.getViaAdministracion() == null ? other.getViaAdministracion() == null : this.getViaAdministracion().equals(other.getViaAdministracion()))
            && (this.getConcentracion() == null ? other.getConcentracion() == null : this.getConcentracion().equals(other.getConcentracion()))
            && (this.getPrincipioActivo() == null ? other.getPrincipioActivo() == null : this.getPrincipioActivo().equals(other.getPrincipioActivo()))
            && (this.getUnidadMedida() == null ? other.getUnidadMedida() == null : this.getUnidadMedida().equals(other.getUnidadMedida()))
            && (this.getCantidad() == null ? other.getCantidad() == null : this.getCantidad().equals(other.getCantidad()))
            && (this.getUnidadReferencia() == null ? other.getUnidadReferencia() == null : this.getUnidadReferencia().equals(other.getUnidadReferencia()))
            && (this.getFormaFarmaceutica() == null ? other.getFormaFarmaceutica() == null : this.getFormaFarmaceutica().equals(other.getFormaFarmaceutica()))
            && (this.getNombreRol() == null ? other.getNombreRol() == null : this.getNombreRol().equals(other.getNombreRol()))
            && (this.getTipoRol() == null ? other.getTipoRol() == null : this.getTipoRol().equals(other.getTipoRol()))
            && (this.getModalidad() == null ? other.getModalidad() == null : this.getModalidad().equals(other.getModalidad()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getExpediente() == null) ? 0 : getExpediente().hashCode());
        result = prime * result + ((getProducto() == null) ? 0 : getProducto().hashCode());
        result = prime * result + ((getTitular() == null) ? 0 : getTitular().hashCode());
        result = prime * result + ((getRegistroSanitario() == null) ? 0 : getRegistroSanitario().hashCode());
        result = prime * result + ((getFechaExpedicion() == null) ? 0 : getFechaExpedicion().hashCode());
        result = prime * result + ((getFechaVencimiento() == null) ? 0 : getFechaVencimiento().hashCode());
        result = prime * result + ((getEstadoRegistro() == null) ? 0 : getEstadoRegistro().hashCode());
        result = prime * result + ((getExpedienteCum() == null) ? 0 : getExpedienteCum().hashCode());
        result = prime * result + ((getConsecutivo() == null) ? 0 : getConsecutivo().hashCode());
        result = prime * result + ((getCantidadCum() == null) ? 0 : getCantidadCum().hashCode());
        result = prime * result + ((getDescripcionComercial() == null) ? 0 : getDescripcionComercial().hashCode());
        result = prime * result + ((getEstadoCum() == null) ? 0 : getEstadoCum().hashCode());
        result = prime * result + ((getFechaActivo() == null) ? 0 : getFechaActivo().hashCode());
        result = prime * result + ((getFechaInactivo() == null) ? 0 : getFechaInactivo().hashCode());
        result = prime * result + ((getMuestraMedica() == null) ? 0 : getMuestraMedica().hashCode());
        result = prime * result + ((getUnidad() == null) ? 0 : getUnidad().hashCode());
        result = prime * result + ((getAtc() == null) ? 0 : getAtc().hashCode());
        result = prime * result + ((getDescripcionAtc() == null) ? 0 : getDescripcionAtc().hashCode());
        result = prime * result + ((getViaAdministracion() == null) ? 0 : getViaAdministracion().hashCode());
        result = prime * result + ((getConcentracion() == null) ? 0 : getConcentracion().hashCode());
        result = prime * result + ((getPrincipioActivo() == null) ? 0 : getPrincipioActivo().hashCode());
        result = prime * result + ((getUnidadMedida() == null) ? 0 : getUnidadMedida().hashCode());
        result = prime * result + ((getCantidad() == null) ? 0 : getCantidad().hashCode());
        result = prime * result + ((getUnidadReferencia() == null) ? 0 : getUnidadReferencia().hashCode());
        result = prime * result + ((getFormaFarmaceutica() == null) ? 0 : getFormaFarmaceutica().hashCode());
        result = prime * result + ((getNombreRol() == null) ? 0 : getNombreRol().hashCode());
        result = prime * result + ((getTipoRol() == null) ? 0 : getTipoRol().hashCode());
        result = prime * result + ((getModalidad() == null) ? 0 : getModalidad().hashCode());
        return result;
    }
}