package co.edu.usc.interacciones.dao.model;

import java.util.ArrayList;
import java.util.List;

public class MedicamentosVigentesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    public MedicamentosVigentesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andExpedienteIsNull() {
            addCriterion("expediente is null");
            return (Criteria) this;
        }

        public Criteria andExpedienteIsNotNull() {
            addCriterion("expediente is not null");
            return (Criteria) this;
        }

        public Criteria andExpedienteEqualTo(String value) {
            addCriterion("expediente =", value, "expediente");
            return (Criteria) this;
        }

        public Criteria andExpedienteNotEqualTo(String value) {
            addCriterion("expediente <>", value, "expediente");
            return (Criteria) this;
        }

        public Criteria andExpedienteGreaterThan(String value) {
            addCriterion("expediente >", value, "expediente");
            return (Criteria) this;
        }

        public Criteria andExpedienteGreaterThanOrEqualTo(String value) {
            addCriterion("expediente >=", value, "expediente");
            return (Criteria) this;
        }

        public Criteria andExpedienteLessThan(String value) {
            addCriterion("expediente <", value, "expediente");
            return (Criteria) this;
        }

        public Criteria andExpedienteLessThanOrEqualTo(String value) {
            addCriterion("expediente <=", value, "expediente");
            return (Criteria) this;
        }

        public Criteria andExpedienteLike(String value) {
            addCriterion("expediente like", value, "expediente");
            return (Criteria) this;
        }

        public Criteria andExpedienteNotLike(String value) {
            addCriterion("expediente not like", value, "expediente");
            return (Criteria) this;
        }

        public Criteria andExpedienteIn(List<String> values) {
            addCriterion("expediente in", values, "expediente");
            return (Criteria) this;
        }

        public Criteria andExpedienteNotIn(List<String> values) {
            addCriterion("expediente not in", values, "expediente");
            return (Criteria) this;
        }

        public Criteria andExpedienteBetween(String value1, String value2) {
            addCriterion("expediente between", value1, value2, "expediente");
            return (Criteria) this;
        }

        public Criteria andExpedienteNotBetween(String value1, String value2) {
            addCriterion("expediente not between", value1, value2, "expediente");
            return (Criteria) this;
        }

        public Criteria andProductoIsNull() {
            addCriterion("producto is null");
            return (Criteria) this;
        }

        public Criteria andProductoIsNotNull() {
            addCriterion("producto is not null");
            return (Criteria) this;
        }

        public Criteria andProductoEqualTo(String value) {
            addCriterion("producto =", value, "producto");
            return (Criteria) this;
        }

        public Criteria andProductoNotEqualTo(String value) {
            addCriterion("producto <>", value, "producto");
            return (Criteria) this;
        }

        public Criteria andProductoGreaterThan(String value) {
            addCriterion("producto >", value, "producto");
            return (Criteria) this;
        }

        public Criteria andProductoGreaterThanOrEqualTo(String value) {
            addCriterion("producto >=", value, "producto");
            return (Criteria) this;
        }

        public Criteria andProductoLessThan(String value) {
            addCriterion("producto <", value, "producto");
            return (Criteria) this;
        }

        public Criteria andProductoLessThanOrEqualTo(String value) {
            addCriterion("producto <=", value, "producto");
            return (Criteria) this;
        }

        public Criteria andProductoLike(String value) {
            addCriterion("producto like", value, "producto");
            return (Criteria) this;
        }

        public Criteria andProductoNotLike(String value) {
            addCriterion("producto not like", value, "producto");
            return (Criteria) this;
        }

        public Criteria andProductoIn(List<String> values) {
            addCriterion("producto in", values, "producto");
            return (Criteria) this;
        }

        public Criteria andProductoNotIn(List<String> values) {
            addCriterion("producto not in", values, "producto");
            return (Criteria) this;
        }

        public Criteria andProductoBetween(String value1, String value2) {
            addCriterion("producto between", value1, value2, "producto");
            return (Criteria) this;
        }

        public Criteria andProductoNotBetween(String value1, String value2) {
            addCriterion("producto not between", value1, value2, "producto");
            return (Criteria) this;
        }

        public Criteria andTitularIsNull() {
            addCriterion("titular is null");
            return (Criteria) this;
        }

        public Criteria andTitularIsNotNull() {
            addCriterion("titular is not null");
            return (Criteria) this;
        }

        public Criteria andTitularEqualTo(String value) {
            addCriterion("titular =", value, "titular");
            return (Criteria) this;
        }

        public Criteria andTitularNotEqualTo(String value) {
            addCriterion("titular <>", value, "titular");
            return (Criteria) this;
        }

        public Criteria andTitularGreaterThan(String value) {
            addCriterion("titular >", value, "titular");
            return (Criteria) this;
        }

        public Criteria andTitularGreaterThanOrEqualTo(String value) {
            addCriterion("titular >=", value, "titular");
            return (Criteria) this;
        }

        public Criteria andTitularLessThan(String value) {
            addCriterion("titular <", value, "titular");
            return (Criteria) this;
        }

        public Criteria andTitularLessThanOrEqualTo(String value) {
            addCriterion("titular <=", value, "titular");
            return (Criteria) this;
        }

        public Criteria andTitularLike(String value) {
            addCriterion("titular like", value, "titular");
            return (Criteria) this;
        }

        public Criteria andTitularNotLike(String value) {
            addCriterion("titular not like", value, "titular");
            return (Criteria) this;
        }

        public Criteria andTitularIn(List<String> values) {
            addCriterion("titular in", values, "titular");
            return (Criteria) this;
        }

        public Criteria andTitularNotIn(List<String> values) {
            addCriterion("titular not in", values, "titular");
            return (Criteria) this;
        }

        public Criteria andTitularBetween(String value1, String value2) {
            addCriterion("titular between", value1, value2, "titular");
            return (Criteria) this;
        }

        public Criteria andTitularNotBetween(String value1, String value2) {
            addCriterion("titular not between", value1, value2, "titular");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioIsNull() {
            addCriterion("registro_sanitario is null");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioIsNotNull() {
            addCriterion("registro_sanitario is not null");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioEqualTo(String value) {
            addCriterion("registro_sanitario =", value, "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioNotEqualTo(String value) {
            addCriterion("registro_sanitario <>", value, "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioGreaterThan(String value) {
            addCriterion("registro_sanitario >", value, "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioGreaterThanOrEqualTo(String value) {
            addCriterion("registro_sanitario >=", value, "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioLessThan(String value) {
            addCriterion("registro_sanitario <", value, "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioLessThanOrEqualTo(String value) {
            addCriterion("registro_sanitario <=", value, "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioLike(String value) {
            addCriterion("registro_sanitario like", value, "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioNotLike(String value) {
            addCriterion("registro_sanitario not like", value, "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioIn(List<String> values) {
            addCriterion("registro_sanitario in", values, "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioNotIn(List<String> values) {
            addCriterion("registro_sanitario not in", values, "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioBetween(String value1, String value2) {
            addCriterion("registro_sanitario between", value1, value2, "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioNotBetween(String value1, String value2) {
            addCriterion("registro_sanitario not between", value1, value2, "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionIsNull() {
            addCriterion("fecha_expedicion is null");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionIsNotNull() {
            addCriterion("fecha_expedicion is not null");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionEqualTo(String value) {
            addCriterion("fecha_expedicion =", value, "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionNotEqualTo(String value) {
            addCriterion("fecha_expedicion <>", value, "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionGreaterThan(String value) {
            addCriterion("fecha_expedicion >", value, "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionGreaterThanOrEqualTo(String value) {
            addCriterion("fecha_expedicion >=", value, "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionLessThan(String value) {
            addCriterion("fecha_expedicion <", value, "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionLessThanOrEqualTo(String value) {
            addCriterion("fecha_expedicion <=", value, "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionLike(String value) {
            addCriterion("fecha_expedicion like", value, "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionNotLike(String value) {
            addCriterion("fecha_expedicion not like", value, "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionIn(List<String> values) {
            addCriterion("fecha_expedicion in", values, "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionNotIn(List<String> values) {
            addCriterion("fecha_expedicion not in", values, "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionBetween(String value1, String value2) {
            addCriterion("fecha_expedicion between", value1, value2, "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionNotBetween(String value1, String value2) {
            addCriterion("fecha_expedicion not between", value1, value2, "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoIsNull() {
            addCriterion("fecha_vencimiento is null");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoIsNotNull() {
            addCriterion("fecha_vencimiento is not null");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoEqualTo(String value) {
            addCriterion("fecha_vencimiento =", value, "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoNotEqualTo(String value) {
            addCriterion("fecha_vencimiento <>", value, "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoGreaterThan(String value) {
            addCriterion("fecha_vencimiento >", value, "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoGreaterThanOrEqualTo(String value) {
            addCriterion("fecha_vencimiento >=", value, "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoLessThan(String value) {
            addCriterion("fecha_vencimiento <", value, "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoLessThanOrEqualTo(String value) {
            addCriterion("fecha_vencimiento <=", value, "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoLike(String value) {
            addCriterion("fecha_vencimiento like", value, "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoNotLike(String value) {
            addCriterion("fecha_vencimiento not like", value, "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoIn(List<String> values) {
            addCriterion("fecha_vencimiento in", values, "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoNotIn(List<String> values) {
            addCriterion("fecha_vencimiento not in", values, "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoBetween(String value1, String value2) {
            addCriterion("fecha_vencimiento between", value1, value2, "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoNotBetween(String value1, String value2) {
            addCriterion("fecha_vencimiento not between", value1, value2, "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroIsNull() {
            addCriterion("estado_registro is null");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroIsNotNull() {
            addCriterion("estado_registro is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroEqualTo(String value) {
            addCriterion("estado_registro =", value, "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroNotEqualTo(String value) {
            addCriterion("estado_registro <>", value, "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroGreaterThan(String value) {
            addCriterion("estado_registro >", value, "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroGreaterThanOrEqualTo(String value) {
            addCriterion("estado_registro >=", value, "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroLessThan(String value) {
            addCriterion("estado_registro <", value, "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroLessThanOrEqualTo(String value) {
            addCriterion("estado_registro <=", value, "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroLike(String value) {
            addCriterion("estado_registro like", value, "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroNotLike(String value) {
            addCriterion("estado_registro not like", value, "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroIn(List<String> values) {
            addCriterion("estado_registro in", values, "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroNotIn(List<String> values) {
            addCriterion("estado_registro not in", values, "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroBetween(String value1, String value2) {
            addCriterion("estado_registro between", value1, value2, "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroNotBetween(String value1, String value2) {
            addCriterion("estado_registro not between", value1, value2, "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumIsNull() {
            addCriterion("expediente_cum is null");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumIsNotNull() {
            addCriterion("expediente_cum is not null");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumEqualTo(String value) {
            addCriterion("expediente_cum =", value, "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumNotEqualTo(String value) {
            addCriterion("expediente_cum <>", value, "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumGreaterThan(String value) {
            addCriterion("expediente_cum >", value, "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumGreaterThanOrEqualTo(String value) {
            addCriterion("expediente_cum >=", value, "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumLessThan(String value) {
            addCriterion("expediente_cum <", value, "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumLessThanOrEqualTo(String value) {
            addCriterion("expediente_cum <=", value, "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumLike(String value) {
            addCriterion("expediente_cum like", value, "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumNotLike(String value) {
            addCriterion("expediente_cum not like", value, "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumIn(List<String> values) {
            addCriterion("expediente_cum in", values, "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumNotIn(List<String> values) {
            addCriterion("expediente_cum not in", values, "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumBetween(String value1, String value2) {
            addCriterion("expediente_cum between", value1, value2, "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumNotBetween(String value1, String value2) {
            addCriterion("expediente_cum not between", value1, value2, "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andConsecutivoIsNull() {
            addCriterion("consecutivo is null");
            return (Criteria) this;
        }

        public Criteria andConsecutivoIsNotNull() {
            addCriterion("consecutivo is not null");
            return (Criteria) this;
        }

        public Criteria andConsecutivoEqualTo(String value) {
            addCriterion("consecutivo =", value, "consecutivo");
            return (Criteria) this;
        }

        public Criteria andConsecutivoNotEqualTo(String value) {
            addCriterion("consecutivo <>", value, "consecutivo");
            return (Criteria) this;
        }

        public Criteria andConsecutivoGreaterThan(String value) {
            addCriterion("consecutivo >", value, "consecutivo");
            return (Criteria) this;
        }

        public Criteria andConsecutivoGreaterThanOrEqualTo(String value) {
            addCriterion("consecutivo >=", value, "consecutivo");
            return (Criteria) this;
        }

        public Criteria andConsecutivoLessThan(String value) {
            addCriterion("consecutivo <", value, "consecutivo");
            return (Criteria) this;
        }

        public Criteria andConsecutivoLessThanOrEqualTo(String value) {
            addCriterion("consecutivo <=", value, "consecutivo");
            return (Criteria) this;
        }

        public Criteria andConsecutivoLike(String value) {
            addCriterion("consecutivo like", value, "consecutivo");
            return (Criteria) this;
        }

        public Criteria andConsecutivoNotLike(String value) {
            addCriterion("consecutivo not like", value, "consecutivo");
            return (Criteria) this;
        }

        public Criteria andConsecutivoIn(List<String> values) {
            addCriterion("consecutivo in", values, "consecutivo");
            return (Criteria) this;
        }

        public Criteria andConsecutivoNotIn(List<String> values) {
            addCriterion("consecutivo not in", values, "consecutivo");
            return (Criteria) this;
        }

        public Criteria andConsecutivoBetween(String value1, String value2) {
            addCriterion("consecutivo between", value1, value2, "consecutivo");
            return (Criteria) this;
        }

        public Criteria andConsecutivoNotBetween(String value1, String value2) {
            addCriterion("consecutivo not between", value1, value2, "consecutivo");
            return (Criteria) this;
        }

        public Criteria andCantidadCumIsNull() {
            addCriterion("cantidad_cum is null");
            return (Criteria) this;
        }

        public Criteria andCantidadCumIsNotNull() {
            addCriterion("cantidad_cum is not null");
            return (Criteria) this;
        }

        public Criteria andCantidadCumEqualTo(String value) {
            addCriterion("cantidad_cum =", value, "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andCantidadCumNotEqualTo(String value) {
            addCriterion("cantidad_cum <>", value, "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andCantidadCumGreaterThan(String value) {
            addCriterion("cantidad_cum >", value, "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andCantidadCumGreaterThanOrEqualTo(String value) {
            addCriterion("cantidad_cum >=", value, "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andCantidadCumLessThan(String value) {
            addCriterion("cantidad_cum <", value, "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andCantidadCumLessThanOrEqualTo(String value) {
            addCriterion("cantidad_cum <=", value, "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andCantidadCumLike(String value) {
            addCriterion("cantidad_cum like", value, "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andCantidadCumNotLike(String value) {
            addCriterion("cantidad_cum not like", value, "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andCantidadCumIn(List<String> values) {
            addCriterion("cantidad_cum in", values, "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andCantidadCumNotIn(List<String> values) {
            addCriterion("cantidad_cum not in", values, "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andCantidadCumBetween(String value1, String value2) {
            addCriterion("cantidad_cum between", value1, value2, "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andCantidadCumNotBetween(String value1, String value2) {
            addCriterion("cantidad_cum not between", value1, value2, "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialIsNull() {
            addCriterion("descripcion_comercial is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialIsNotNull() {
            addCriterion("descripcion_comercial is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialEqualTo(String value) {
            addCriterion("descripcion_comercial =", value, "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialNotEqualTo(String value) {
            addCriterion("descripcion_comercial <>", value, "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialGreaterThan(String value) {
            addCriterion("descripcion_comercial >", value, "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion_comercial >=", value, "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialLessThan(String value) {
            addCriterion("descripcion_comercial <", value, "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialLessThanOrEqualTo(String value) {
            addCriterion("descripcion_comercial <=", value, "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialLike(String value) {
            addCriterion("descripcion_comercial like", value, "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialNotLike(String value) {
            addCriterion("descripcion_comercial not like", value, "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialIn(List<String> values) {
            addCriterion("descripcion_comercial in", values, "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialNotIn(List<String> values) {
            addCriterion("descripcion_comercial not in", values, "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialBetween(String value1, String value2) {
            addCriterion("descripcion_comercial between", value1, value2, "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialNotBetween(String value1, String value2) {
            addCriterion("descripcion_comercial not between", value1, value2, "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andEstadoCumIsNull() {
            addCriterion("estado_cum is null");
            return (Criteria) this;
        }

        public Criteria andEstadoCumIsNotNull() {
            addCriterion("estado_cum is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoCumEqualTo(String value) {
            addCriterion("estado_cum =", value, "estadoCum");
            return (Criteria) this;
        }

        public Criteria andEstadoCumNotEqualTo(String value) {
            addCriterion("estado_cum <>", value, "estadoCum");
            return (Criteria) this;
        }

        public Criteria andEstadoCumGreaterThan(String value) {
            addCriterion("estado_cum >", value, "estadoCum");
            return (Criteria) this;
        }

        public Criteria andEstadoCumGreaterThanOrEqualTo(String value) {
            addCriterion("estado_cum >=", value, "estadoCum");
            return (Criteria) this;
        }

        public Criteria andEstadoCumLessThan(String value) {
            addCriterion("estado_cum <", value, "estadoCum");
            return (Criteria) this;
        }

        public Criteria andEstadoCumLessThanOrEqualTo(String value) {
            addCriterion("estado_cum <=", value, "estadoCum");
            return (Criteria) this;
        }

        public Criteria andEstadoCumLike(String value) {
            addCriterion("estado_cum like", value, "estadoCum");
            return (Criteria) this;
        }

        public Criteria andEstadoCumNotLike(String value) {
            addCriterion("estado_cum not like", value, "estadoCum");
            return (Criteria) this;
        }

        public Criteria andEstadoCumIn(List<String> values) {
            addCriterion("estado_cum in", values, "estadoCum");
            return (Criteria) this;
        }

        public Criteria andEstadoCumNotIn(List<String> values) {
            addCriterion("estado_cum not in", values, "estadoCum");
            return (Criteria) this;
        }

        public Criteria andEstadoCumBetween(String value1, String value2) {
            addCriterion("estado_cum between", value1, value2, "estadoCum");
            return (Criteria) this;
        }

        public Criteria andEstadoCumNotBetween(String value1, String value2) {
            addCriterion("estado_cum not between", value1, value2, "estadoCum");
            return (Criteria) this;
        }

        public Criteria andFechaActivoIsNull() {
            addCriterion("fecha_activo is null");
            return (Criteria) this;
        }

        public Criteria andFechaActivoIsNotNull() {
            addCriterion("fecha_activo is not null");
            return (Criteria) this;
        }

        public Criteria andFechaActivoEqualTo(String value) {
            addCriterion("fecha_activo =", value, "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaActivoNotEqualTo(String value) {
            addCriterion("fecha_activo <>", value, "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaActivoGreaterThan(String value) {
            addCriterion("fecha_activo >", value, "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaActivoGreaterThanOrEqualTo(String value) {
            addCriterion("fecha_activo >=", value, "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaActivoLessThan(String value) {
            addCriterion("fecha_activo <", value, "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaActivoLessThanOrEqualTo(String value) {
            addCriterion("fecha_activo <=", value, "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaActivoLike(String value) {
            addCriterion("fecha_activo like", value, "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaActivoNotLike(String value) {
            addCriterion("fecha_activo not like", value, "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaActivoIn(List<String> values) {
            addCriterion("fecha_activo in", values, "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaActivoNotIn(List<String> values) {
            addCriterion("fecha_activo not in", values, "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaActivoBetween(String value1, String value2) {
            addCriterion("fecha_activo between", value1, value2, "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaActivoNotBetween(String value1, String value2) {
            addCriterion("fecha_activo not between", value1, value2, "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoIsNull() {
            addCriterion("fecha_inactivo is null");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoIsNotNull() {
            addCriterion("fecha_inactivo is not null");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoEqualTo(String value) {
            addCriterion("fecha_inactivo =", value, "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoNotEqualTo(String value) {
            addCriterion("fecha_inactivo <>", value, "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoGreaterThan(String value) {
            addCriterion("fecha_inactivo >", value, "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoGreaterThanOrEqualTo(String value) {
            addCriterion("fecha_inactivo >=", value, "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoLessThan(String value) {
            addCriterion("fecha_inactivo <", value, "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoLessThanOrEqualTo(String value) {
            addCriterion("fecha_inactivo <=", value, "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoLike(String value) {
            addCriterion("fecha_inactivo like", value, "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoNotLike(String value) {
            addCriterion("fecha_inactivo not like", value, "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoIn(List<String> values) {
            addCriterion("fecha_inactivo in", values, "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoNotIn(List<String> values) {
            addCriterion("fecha_inactivo not in", values, "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoBetween(String value1, String value2) {
            addCriterion("fecha_inactivo between", value1, value2, "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoNotBetween(String value1, String value2) {
            addCriterion("fecha_inactivo not between", value1, value2, "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaIsNull() {
            addCriterion("muestra_medica is null");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaIsNotNull() {
            addCriterion("muestra_medica is not null");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaEqualTo(String value) {
            addCriterion("muestra_medica =", value, "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaNotEqualTo(String value) {
            addCriterion("muestra_medica <>", value, "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaGreaterThan(String value) {
            addCriterion("muestra_medica >", value, "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaGreaterThanOrEqualTo(String value) {
            addCriterion("muestra_medica >=", value, "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaLessThan(String value) {
            addCriterion("muestra_medica <", value, "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaLessThanOrEqualTo(String value) {
            addCriterion("muestra_medica <=", value, "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaLike(String value) {
            addCriterion("muestra_medica like", value, "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaNotLike(String value) {
            addCriterion("muestra_medica not like", value, "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaIn(List<String> values) {
            addCriterion("muestra_medica in", values, "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaNotIn(List<String> values) {
            addCriterion("muestra_medica not in", values, "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaBetween(String value1, String value2) {
            addCriterion("muestra_medica between", value1, value2, "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaNotBetween(String value1, String value2) {
            addCriterion("muestra_medica not between", value1, value2, "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andUnidadIsNull() {
            addCriterion("unidad is null");
            return (Criteria) this;
        }

        public Criteria andUnidadIsNotNull() {
            addCriterion("unidad is not null");
            return (Criteria) this;
        }

        public Criteria andUnidadEqualTo(String value) {
            addCriterion("unidad =", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadNotEqualTo(String value) {
            addCriterion("unidad <>", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadGreaterThan(String value) {
            addCriterion("unidad >", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadGreaterThanOrEqualTo(String value) {
            addCriterion("unidad >=", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadLessThan(String value) {
            addCriterion("unidad <", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadLessThanOrEqualTo(String value) {
            addCriterion("unidad <=", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadLike(String value) {
            addCriterion("unidad like", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadNotLike(String value) {
            addCriterion("unidad not like", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadIn(List<String> values) {
            addCriterion("unidad in", values, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadNotIn(List<String> values) {
            addCriterion("unidad not in", values, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadBetween(String value1, String value2) {
            addCriterion("unidad between", value1, value2, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadNotBetween(String value1, String value2) {
            addCriterion("unidad not between", value1, value2, "unidad");
            return (Criteria) this;
        }

        public Criteria andAtcIsNull() {
            addCriterion("atc is null");
            return (Criteria) this;
        }

        public Criteria andAtcIsNotNull() {
            addCriterion("atc is not null");
            return (Criteria) this;
        }

        public Criteria andAtcEqualTo(String value) {
            addCriterion("atc =", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcNotEqualTo(String value) {
            addCriterion("atc <>", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcGreaterThan(String value) {
            addCriterion("atc >", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcGreaterThanOrEqualTo(String value) {
            addCriterion("atc >=", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcLessThan(String value) {
            addCriterion("atc <", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcLessThanOrEqualTo(String value) {
            addCriterion("atc <=", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcLike(String value) {
            addCriterion("atc like", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcNotLike(String value) {
            addCriterion("atc not like", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcIn(List<String> values) {
            addCriterion("atc in", values, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcNotIn(List<String> values) {
            addCriterion("atc not in", values, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcBetween(String value1, String value2) {
            addCriterion("atc between", value1, value2, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcNotBetween(String value1, String value2) {
            addCriterion("atc not between", value1, value2, "atc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcIsNull() {
            addCriterion("descripcion_atc is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcIsNotNull() {
            addCriterion("descripcion_atc is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcEqualTo(String value) {
            addCriterion("descripcion_atc =", value, "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcNotEqualTo(String value) {
            addCriterion("descripcion_atc <>", value, "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcGreaterThan(String value) {
            addCriterion("descripcion_atc >", value, "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion_atc >=", value, "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcLessThan(String value) {
            addCriterion("descripcion_atc <", value, "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcLessThanOrEqualTo(String value) {
            addCriterion("descripcion_atc <=", value, "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcLike(String value) {
            addCriterion("descripcion_atc like", value, "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcNotLike(String value) {
            addCriterion("descripcion_atc not like", value, "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcIn(List<String> values) {
            addCriterion("descripcion_atc in", values, "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcNotIn(List<String> values) {
            addCriterion("descripcion_atc not in", values, "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcBetween(String value1, String value2) {
            addCriterion("descripcion_atc between", value1, value2, "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcNotBetween(String value1, String value2) {
            addCriterion("descripcion_atc not between", value1, value2, "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionIsNull() {
            addCriterion("via_administracion is null");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionIsNotNull() {
            addCriterion("via_administracion is not null");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionEqualTo(String value) {
            addCriterion("via_administracion =", value, "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionNotEqualTo(String value) {
            addCriterion("via_administracion <>", value, "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionGreaterThan(String value) {
            addCriterion("via_administracion >", value, "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionGreaterThanOrEqualTo(String value) {
            addCriterion("via_administracion >=", value, "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionLessThan(String value) {
            addCriterion("via_administracion <", value, "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionLessThanOrEqualTo(String value) {
            addCriterion("via_administracion <=", value, "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionLike(String value) {
            addCriterion("via_administracion like", value, "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionNotLike(String value) {
            addCriterion("via_administracion not like", value, "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionIn(List<String> values) {
            addCriterion("via_administracion in", values, "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionNotIn(List<String> values) {
            addCriterion("via_administracion not in", values, "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionBetween(String value1, String value2) {
            addCriterion("via_administracion between", value1, value2, "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionNotBetween(String value1, String value2) {
            addCriterion("via_administracion not between", value1, value2, "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionIsNull() {
            addCriterion("concentracion is null");
            return (Criteria) this;
        }

        public Criteria andConcentracionIsNotNull() {
            addCriterion("concentracion is not null");
            return (Criteria) this;
        }

        public Criteria andConcentracionEqualTo(String value) {
            addCriterion("concentracion =", value, "concentracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionNotEqualTo(String value) {
            addCriterion("concentracion <>", value, "concentracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionGreaterThan(String value) {
            addCriterion("concentracion >", value, "concentracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionGreaterThanOrEqualTo(String value) {
            addCriterion("concentracion >=", value, "concentracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionLessThan(String value) {
            addCriterion("concentracion <", value, "concentracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionLessThanOrEqualTo(String value) {
            addCriterion("concentracion <=", value, "concentracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionLike(String value) {
            addCriterion("concentracion like", value, "concentracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionNotLike(String value) {
            addCriterion("concentracion not like", value, "concentracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionIn(List<String> values) {
            addCriterion("concentracion in", values, "concentracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionNotIn(List<String> values) {
            addCriterion("concentracion not in", values, "concentracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionBetween(String value1, String value2) {
            addCriterion("concentracion between", value1, value2, "concentracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionNotBetween(String value1, String value2) {
            addCriterion("concentracion not between", value1, value2, "concentracion");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoIsNull() {
            addCriterion("principio_activo is null");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoIsNotNull() {
            addCriterion("principio_activo is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoEqualTo(String value) {
            addCriterion("principio_activo =", value, "principioActivo");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoNotEqualTo(String value) {
            addCriterion("principio_activo <>", value, "principioActivo");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoGreaterThan(String value) {
            addCriterion("principio_activo >", value, "principioActivo");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoGreaterThanOrEqualTo(String value) {
            addCriterion("principio_activo >=", value, "principioActivo");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoLessThan(String value) {
            addCriterion("principio_activo <", value, "principioActivo");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoLessThanOrEqualTo(String value) {
            addCriterion("principio_activo <=", value, "principioActivo");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoLike(String value) {
            addCriterion("principio_activo like", value, "principioActivo");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoNotLike(String value) {
            addCriterion("principio_activo not like", value, "principioActivo");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoIn(List<String> values) {
            addCriterion("principio_activo in", values, "principioActivo");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoNotIn(List<String> values) {
            addCriterion("principio_activo not in", values, "principioActivo");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoBetween(String value1, String value2) {
            addCriterion("principio_activo between", value1, value2, "principioActivo");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoNotBetween(String value1, String value2) {
            addCriterion("principio_activo not between", value1, value2, "principioActivo");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaIsNull() {
            addCriterion("unidad_medida is null");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaIsNotNull() {
            addCriterion("unidad_medida is not null");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaEqualTo(String value) {
            addCriterion("unidad_medida =", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaNotEqualTo(String value) {
            addCriterion("unidad_medida <>", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaGreaterThan(String value) {
            addCriterion("unidad_medida >", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaGreaterThanOrEqualTo(String value) {
            addCriterion("unidad_medida >=", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaLessThan(String value) {
            addCriterion("unidad_medida <", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaLessThanOrEqualTo(String value) {
            addCriterion("unidad_medida <=", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaLike(String value) {
            addCriterion("unidad_medida like", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaNotLike(String value) {
            addCriterion("unidad_medida not like", value, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaIn(List<String> values) {
            addCriterion("unidad_medida in", values, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaNotIn(List<String> values) {
            addCriterion("unidad_medida not in", values, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaBetween(String value1, String value2) {
            addCriterion("unidad_medida between", value1, value2, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaNotBetween(String value1, String value2) {
            addCriterion("unidad_medida not between", value1, value2, "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andCantidadIsNull() {
            addCriterion("cantidad is null");
            return (Criteria) this;
        }

        public Criteria andCantidadIsNotNull() {
            addCriterion("cantidad is not null");
            return (Criteria) this;
        }

        public Criteria andCantidadEqualTo(String value) {
            addCriterion("cantidad =", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotEqualTo(String value) {
            addCriterion("cantidad <>", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadGreaterThan(String value) {
            addCriterion("cantidad >", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadGreaterThanOrEqualTo(String value) {
            addCriterion("cantidad >=", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadLessThan(String value) {
            addCriterion("cantidad <", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadLessThanOrEqualTo(String value) {
            addCriterion("cantidad <=", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadLike(String value) {
            addCriterion("cantidad like", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotLike(String value) {
            addCriterion("cantidad not like", value, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadIn(List<String> values) {
            addCriterion("cantidad in", values, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotIn(List<String> values) {
            addCriterion("cantidad not in", values, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadBetween(String value1, String value2) {
            addCriterion("cantidad between", value1, value2, "cantidad");
            return (Criteria) this;
        }

        public Criteria andCantidadNotBetween(String value1, String value2) {
            addCriterion("cantidad not between", value1, value2, "cantidad");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaIsNull() {
            addCriterion("unidad_referencia is null");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaIsNotNull() {
            addCriterion("unidad_referencia is not null");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaEqualTo(String value) {
            addCriterion("unidad_referencia =", value, "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaNotEqualTo(String value) {
            addCriterion("unidad_referencia <>", value, "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaGreaterThan(String value) {
            addCriterion("unidad_referencia >", value, "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaGreaterThanOrEqualTo(String value) {
            addCriterion("unidad_referencia >=", value, "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaLessThan(String value) {
            addCriterion("unidad_referencia <", value, "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaLessThanOrEqualTo(String value) {
            addCriterion("unidad_referencia <=", value, "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaLike(String value) {
            addCriterion("unidad_referencia like", value, "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaNotLike(String value) {
            addCriterion("unidad_referencia not like", value, "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaIn(List<String> values) {
            addCriterion("unidad_referencia in", values, "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaNotIn(List<String> values) {
            addCriterion("unidad_referencia not in", values, "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaBetween(String value1, String value2) {
            addCriterion("unidad_referencia between", value1, value2, "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaNotBetween(String value1, String value2) {
            addCriterion("unidad_referencia not between", value1, value2, "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaIsNull() {
            addCriterion("forma_farmaceutica is null");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaIsNotNull() {
            addCriterion("forma_farmaceutica is not null");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaEqualTo(String value) {
            addCriterion("forma_farmaceutica =", value, "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaNotEqualTo(String value) {
            addCriterion("forma_farmaceutica <>", value, "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaGreaterThan(String value) {
            addCriterion("forma_farmaceutica >", value, "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaGreaterThanOrEqualTo(String value) {
            addCriterion("forma_farmaceutica >=", value, "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaLessThan(String value) {
            addCriterion("forma_farmaceutica <", value, "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaLessThanOrEqualTo(String value) {
            addCriterion("forma_farmaceutica <=", value, "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaLike(String value) {
            addCriterion("forma_farmaceutica like", value, "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaNotLike(String value) {
            addCriterion("forma_farmaceutica not like", value, "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaIn(List<String> values) {
            addCriterion("forma_farmaceutica in", values, "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaNotIn(List<String> values) {
            addCriterion("forma_farmaceutica not in", values, "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaBetween(String value1, String value2) {
            addCriterion("forma_farmaceutica between", value1, value2, "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaNotBetween(String value1, String value2) {
            addCriterion("forma_farmaceutica not between", value1, value2, "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andNombreRolIsNull() {
            addCriterion("nombre_rol is null");
            return (Criteria) this;
        }

        public Criteria andNombreRolIsNotNull() {
            addCriterion("nombre_rol is not null");
            return (Criteria) this;
        }

        public Criteria andNombreRolEqualTo(String value) {
            addCriterion("nombre_rol =", value, "nombreRol");
            return (Criteria) this;
        }

        public Criteria andNombreRolNotEqualTo(String value) {
            addCriterion("nombre_rol <>", value, "nombreRol");
            return (Criteria) this;
        }

        public Criteria andNombreRolGreaterThan(String value) {
            addCriterion("nombre_rol >", value, "nombreRol");
            return (Criteria) this;
        }

        public Criteria andNombreRolGreaterThanOrEqualTo(String value) {
            addCriterion("nombre_rol >=", value, "nombreRol");
            return (Criteria) this;
        }

        public Criteria andNombreRolLessThan(String value) {
            addCriterion("nombre_rol <", value, "nombreRol");
            return (Criteria) this;
        }

        public Criteria andNombreRolLessThanOrEqualTo(String value) {
            addCriterion("nombre_rol <=", value, "nombreRol");
            return (Criteria) this;
        }

        public Criteria andNombreRolLike(String value) {
            addCriterion("nombre_rol like", value, "nombreRol");
            return (Criteria) this;
        }

        public Criteria andNombreRolNotLike(String value) {
            addCriterion("nombre_rol not like", value, "nombreRol");
            return (Criteria) this;
        }

        public Criteria andNombreRolIn(List<String> values) {
            addCriterion("nombre_rol in", values, "nombreRol");
            return (Criteria) this;
        }

        public Criteria andNombreRolNotIn(List<String> values) {
            addCriterion("nombre_rol not in", values, "nombreRol");
            return (Criteria) this;
        }

        public Criteria andNombreRolBetween(String value1, String value2) {
            addCriterion("nombre_rol between", value1, value2, "nombreRol");
            return (Criteria) this;
        }

        public Criteria andNombreRolNotBetween(String value1, String value2) {
            addCriterion("nombre_rol not between", value1, value2, "nombreRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolIsNull() {
            addCriterion("tipo_rol is null");
            return (Criteria) this;
        }

        public Criteria andTipoRolIsNotNull() {
            addCriterion("tipo_rol is not null");
            return (Criteria) this;
        }

        public Criteria andTipoRolEqualTo(String value) {
            addCriterion("tipo_rol =", value, "tipoRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolNotEqualTo(String value) {
            addCriterion("tipo_rol <>", value, "tipoRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolGreaterThan(String value) {
            addCriterion("tipo_rol >", value, "tipoRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolGreaterThanOrEqualTo(String value) {
            addCriterion("tipo_rol >=", value, "tipoRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolLessThan(String value) {
            addCriterion("tipo_rol <", value, "tipoRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolLessThanOrEqualTo(String value) {
            addCriterion("tipo_rol <=", value, "tipoRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolLike(String value) {
            addCriterion("tipo_rol like", value, "tipoRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolNotLike(String value) {
            addCriterion("tipo_rol not like", value, "tipoRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolIn(List<String> values) {
            addCriterion("tipo_rol in", values, "tipoRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolNotIn(List<String> values) {
            addCriterion("tipo_rol not in", values, "tipoRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolBetween(String value1, String value2) {
            addCriterion("tipo_rol between", value1, value2, "tipoRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolNotBetween(String value1, String value2) {
            addCriterion("tipo_rol not between", value1, value2, "tipoRol");
            return (Criteria) this;
        }

        public Criteria andModalidadIsNull() {
            addCriterion("modalidad is null");
            return (Criteria) this;
        }

        public Criteria andModalidadIsNotNull() {
            addCriterion("modalidad is not null");
            return (Criteria) this;
        }

        public Criteria andModalidadEqualTo(String value) {
            addCriterion("modalidad =", value, "modalidad");
            return (Criteria) this;
        }

        public Criteria andModalidadNotEqualTo(String value) {
            addCriterion("modalidad <>", value, "modalidad");
            return (Criteria) this;
        }

        public Criteria andModalidadGreaterThan(String value) {
            addCriterion("modalidad >", value, "modalidad");
            return (Criteria) this;
        }

        public Criteria andModalidadGreaterThanOrEqualTo(String value) {
            addCriterion("modalidad >=", value, "modalidad");
            return (Criteria) this;
        }

        public Criteria andModalidadLessThan(String value) {
            addCriterion("modalidad <", value, "modalidad");
            return (Criteria) this;
        }

        public Criteria andModalidadLessThanOrEqualTo(String value) {
            addCriterion("modalidad <=", value, "modalidad");
            return (Criteria) this;
        }

        public Criteria andModalidadLike(String value) {
            addCriterion("modalidad like", value, "modalidad");
            return (Criteria) this;
        }

        public Criteria andModalidadNotLike(String value) {
            addCriterion("modalidad not like", value, "modalidad");
            return (Criteria) this;
        }

        public Criteria andModalidadIn(List<String> values) {
            addCriterion("modalidad in", values, "modalidad");
            return (Criteria) this;
        }

        public Criteria andModalidadNotIn(List<String> values) {
            addCriterion("modalidad not in", values, "modalidad");
            return (Criteria) this;
        }

        public Criteria andModalidadBetween(String value1, String value2) {
            addCriterion("modalidad between", value1, value2, "modalidad");
            return (Criteria) this;
        }

        public Criteria andModalidadNotBetween(String value1, String value2) {
            addCriterion("modalidad not between", value1, value2, "modalidad");
            return (Criteria) this;
        }

        public Criteria andExpedienteLikeInsensitive(String value) {
            addCriterion("upper(expediente) like", value.toUpperCase(), "expediente");
            return (Criteria) this;
        }

        public Criteria andProductoLikeInsensitive(String value) {
            addCriterion("upper(producto) like", value.toUpperCase(), "producto");
            return (Criteria) this;
        }

        public Criteria andTitularLikeInsensitive(String value) {
            addCriterion("upper(titular) like", value.toUpperCase(), "titular");
            return (Criteria) this;
        }

        public Criteria andRegistroSanitarioLikeInsensitive(String value) {
            addCriterion("upper(registro_sanitario) like", value.toUpperCase(), "registroSanitario");
            return (Criteria) this;
        }

        public Criteria andFechaExpedicionLikeInsensitive(String value) {
            addCriterion("upper(fecha_expedicion) like", value.toUpperCase(), "fechaExpedicion");
            return (Criteria) this;
        }

        public Criteria andFechaVencimientoLikeInsensitive(String value) {
            addCriterion("upper(fecha_vencimiento) like", value.toUpperCase(), "fechaVencimiento");
            return (Criteria) this;
        }

        public Criteria andEstadoRegistroLikeInsensitive(String value) {
            addCriterion("upper(estado_registro) like", value.toUpperCase(), "estadoRegistro");
            return (Criteria) this;
        }

        public Criteria andExpedienteCumLikeInsensitive(String value) {
            addCriterion("upper(expediente_cum) like", value.toUpperCase(), "expedienteCum");
            return (Criteria) this;
        }

        public Criteria andConsecutivoLikeInsensitive(String value) {
            addCriterion("upper(consecutivo) like", value.toUpperCase(), "consecutivo");
            return (Criteria) this;
        }

        public Criteria andCantidadCumLikeInsensitive(String value) {
            addCriterion("upper(cantidad_cum) like", value.toUpperCase(), "cantidadCum");
            return (Criteria) this;
        }

        public Criteria andDescripcionComercialLikeInsensitive(String value) {
            addCriterion("upper(descripcion_comercial) like", value.toUpperCase(), "descripcionComercial");
            return (Criteria) this;
        }

        public Criteria andEstadoCumLikeInsensitive(String value) {
            addCriterion("upper(estado_cum) like", value.toUpperCase(), "estadoCum");
            return (Criteria) this;
        }

        public Criteria andFechaActivoLikeInsensitive(String value) {
            addCriterion("upper(fecha_activo) like", value.toUpperCase(), "fechaActivo");
            return (Criteria) this;
        }

        public Criteria andFechaInactivoLikeInsensitive(String value) {
            addCriterion("upper(fecha_inactivo) like", value.toUpperCase(), "fechaInactivo");
            return (Criteria) this;
        }

        public Criteria andMuestraMedicaLikeInsensitive(String value) {
            addCriterion("upper(muestra_medica) like", value.toUpperCase(), "muestraMedica");
            return (Criteria) this;
        }

        public Criteria andUnidadLikeInsensitive(String value) {
            addCriterion("upper(unidad) like", value.toUpperCase(), "unidad");
            return (Criteria) this;
        }

        public Criteria andAtcLikeInsensitive(String value) {
            addCriterion("upper(atc) like", value.toUpperCase(), "atc");
            return (Criteria) this;
        }

        public Criteria andDescripcionAtcLikeInsensitive(String value) {
            addCriterion("upper(descripcion_atc) like", value.toUpperCase(), "descripcionAtc");
            return (Criteria) this;
        }

        public Criteria andViaAdministracionLikeInsensitive(String value) {
            addCriterion("upper(via_administracion) like", value.toUpperCase(), "viaAdministracion");
            return (Criteria) this;
        }

        public Criteria andConcentracionLikeInsensitive(String value) {
            addCriterion("upper(concentracion) like", value.toUpperCase(), "concentracion");
            return (Criteria) this;
        }

        public Criteria andPrincipioActivoLikeInsensitive(String value) {
            addCriterion("upper(principio_activo) like", value.toUpperCase(), "principioActivo");
            return (Criteria) this;
        }

        public Criteria andUnidadMedidaLikeInsensitive(String value) {
            addCriterion("upper(unidad_medida) like", value.toUpperCase(), "unidadMedida");
            return (Criteria) this;
        }

        public Criteria andCantidadLikeInsensitive(String value) {
            addCriterion("upper(cantidad) like", value.toUpperCase(), "cantidad");
            return (Criteria) this;
        }

        public Criteria andUnidadReferenciaLikeInsensitive(String value) {
            addCriterion("upper(unidad_referencia) like", value.toUpperCase(), "unidadReferencia");
            return (Criteria) this;
        }

        public Criteria andFormaFarmaceuticaLikeInsensitive(String value) {
            addCriterion("upper(forma_farmaceutica) like", value.toUpperCase(), "formaFarmaceutica");
            return (Criteria) this;
        }

        public Criteria andNombreRolLikeInsensitive(String value) {
            addCriterion("upper(nombre_rol) like", value.toUpperCase(), "nombreRol");
            return (Criteria) this;
        }

        public Criteria andTipoRolLikeInsensitive(String value) {
            addCriterion("upper(tipo_rol) like", value.toUpperCase(), "tipoRol");
            return (Criteria) this;
        }

        public Criteria andModalidadLikeInsensitive(String value) {
            addCriterion("upper(modalidad) like", value.toUpperCase(), "modalidad");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}