package co.edu.usc.interacciones.dao.model;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MedicamentosVigentesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    int countByExample(MedicamentosVigentesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    int deleteByExample(MedicamentosVigentesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    int insert(MedicamentosVigentes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    int insertSelective(MedicamentosVigentes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    List<MedicamentosVigentes> selectByExample(MedicamentosVigentesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MedicamentosVigentes record, @Param("example") MedicamentosVigentesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicamentos_vigentes
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MedicamentosVigentes record, @Param("example") MedicamentosVigentesExample example);
}