package co.edu.usc.interacciones.dao.model;

import java.io.Serializable;

public class MoleculasTargets implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table moleculas_targets
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moleculas_targets.farget
     *
     * @mbggenerated
     */
    private Integer farget;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moleculas_targets.efecto
     *
     * @mbggenerated
     */
    private Short efecto;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moleculas_targets.molecula
     *
     * @mbggenerated
     */
    private Long molecula;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moleculas_targets.farget
     *
     * @return the value of moleculas_targets.farget
     *
     * @mbggenerated
     */
    public Integer getFarget() {
        return farget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moleculas_targets.farget
     *
     * @param farget the value for moleculas_targets.farget
     *
     * @mbggenerated
     */
    public void setFarget(Integer farget) {
        this.farget = farget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moleculas_targets.efecto
     *
     * @return the value of moleculas_targets.efecto
     *
     * @mbggenerated
     */
    public Short getEfecto() {
        return efecto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moleculas_targets.efecto
     *
     * @param efecto the value for moleculas_targets.efecto
     *
     * @mbggenerated
     */
    public void setEfecto(Short efecto) {
        this.efecto = efecto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moleculas_targets.molecula
     *
     * @return the value of moleculas_targets.molecula
     *
     * @mbggenerated
     */
    public Long getMolecula() {
        return molecula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moleculas_targets.molecula
     *
     * @param molecula the value for moleculas_targets.molecula
     *
     * @mbggenerated
     */
    public void setMolecula(Long molecula) {
        this.molecula = molecula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas_targets
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MoleculasTargets other = (MoleculasTargets) that;
        return (this.getFarget() == null ? other.getFarget() == null : this.getFarget().equals(other.getFarget()))
                && (this.getEfecto() == null ? other.getEfecto() == null : this.getEfecto().equals(other.getEfecto()))
                && (this.getMolecula() == null ? other.getMolecula() == null : this.getMolecula().equals(other.getMolecula()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas_targets
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFarget() == null) ? 0 : getFarget().hashCode());
        result = prime * result + ((getEfecto() == null) ? 0 : getEfecto().hashCode());
        result = prime * result + ((getMolecula() == null) ? 0 : getMolecula().hashCode());
        return result;
    }
}