package co.edu.usc.interacciones.dao.model;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MoleculasTargetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas_targets
     *
     * @mbggenerated
     */
    int countByExample(MoleculasTargetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas_targets
     *
     * @mbggenerated
     */
    int deleteByExample(MoleculasTargetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas_targets
     *
     * @mbggenerated
     */
    int insert(MoleculasTargets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas_targets
     *
     * @mbggenerated
     */
    int insertSelective(MoleculasTargets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas_targets
     *
     * @mbggenerated
     */
    List<MoleculasTargets> selectByExample(MoleculasTargetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas_targets
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MoleculasTargets record, @Param("example") MoleculasTargetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas_targets
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MoleculasTargets record, @Param("example") MoleculasTargetsExample example);
}