package co.edu.usc.interacciones.dao.model;

import co.edu.usc.interacciones.dao.model.Moleculas;
import co.edu.usc.interacciones.dao.model.MoleculasExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MoleculasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas
     *
     * @mbggenerated
     */
    int countByExample(MoleculasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas
     *
     * @mbggenerated
     */
    int deleteByExample(MoleculasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long idmoleculas);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas
     *
     * @mbggenerated
     */
    int insert(Moleculas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas
     *
     * @mbggenerated
     */
    int insertSelective(Moleculas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas
     *
     * @mbggenerated
     */
    List<Moleculas> selectByExample(MoleculasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas
     *
     * @mbggenerated
     */
    Moleculas selectByPrimaryKey(Long idmoleculas);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Moleculas record, @Param("example") MoleculasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Moleculas record, @Param("example") MoleculasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Moleculas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moleculas
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Moleculas record);
}