package co.edu.usc.interacciones.dao.model;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MoleculasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas
     *
     * @mbggenerated
     */
    int countByExample(MoleculasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas
     *
     * @mbggenerated
     */
    int deleteByExample(MoleculasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas
     *
     * @mbggenerated
     */
    int insert(Moleculas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas
     *
     * @mbggenerated
     */
    int insertSelective(Moleculas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas
     *
     * @mbggenerated
     */
    List<Moleculas> selectByExample(MoleculasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Moleculas record, @Param("example") MoleculasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.moleculas
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Moleculas record, @Param("example") MoleculasExample example);
}