package co.edu.usc.interacciones.dao.model;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PresentacionesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.presentaciones
     *
     * @mbggenerated
     */
    int countByExample(PresentacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.presentaciones
     *
     * @mbggenerated
     */
    int deleteByExample(PresentacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.presentaciones
     *
     * @mbggenerated
     */
    int insert(Presentaciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.presentaciones
     *
     * @mbggenerated
     */
    int insertSelective(Presentaciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.presentaciones
     *
     * @mbggenerated
     */
    List<Presentaciones> selectByExample(PresentacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.presentaciones
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Presentaciones record, @Param("example") PresentacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.presentaciones
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Presentaciones record, @Param("example") PresentacionesExample example);
}