package co.edu.usc.interacciones.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RegistrossanitariosExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    public RegistrossanitariosExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdcodigoinvimaIsNull() {
            addCriterion("idcodigoinvima is null");
            return (Criteria) this;
        }

        public Criteria andIdcodigoinvimaIsNotNull() {
            addCriterion("idcodigoinvima is not null");
            return (Criteria) this;
        }

        public Criteria andIdcodigoinvimaEqualTo(BigDecimal value) {
            addCriterion("idcodigoinvima =", value, "idcodigoinvima");
            return (Criteria) this;
        }

        public Criteria andIdcodigoinvimaNotEqualTo(BigDecimal value) {
            addCriterion("idcodigoinvima <>", value, "idcodigoinvima");
            return (Criteria) this;
        }

        public Criteria andIdcodigoinvimaGreaterThan(BigDecimal value) {
            addCriterion("idcodigoinvima >", value, "idcodigoinvima");
            return (Criteria) this;
        }

        public Criteria andIdcodigoinvimaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("idcodigoinvima >=", value, "idcodigoinvima");
            return (Criteria) this;
        }

        public Criteria andIdcodigoinvimaLessThan(BigDecimal value) {
            addCriterion("idcodigoinvima <", value, "idcodigoinvima");
            return (Criteria) this;
        }

        public Criteria andIdcodigoinvimaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("idcodigoinvima <=", value, "idcodigoinvima");
            return (Criteria) this;
        }

        public Criteria andIdcodigoinvimaIn(List<BigDecimal> values) {
            addCriterion("idcodigoinvima in", values, "idcodigoinvima");
            return (Criteria) this;
        }

        public Criteria andIdcodigoinvimaNotIn(List<BigDecimal> values) {
            addCriterion("idcodigoinvima not in", values, "idcodigoinvima");
            return (Criteria) this;
        }

        public Criteria andIdcodigoinvimaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("idcodigoinvima between", value1, value2, "idcodigoinvima");
            return (Criteria) this;
        }

        public Criteria andIdcodigoinvimaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("idcodigoinvima not between", value1, value2, "idcodigoinvima");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaIsNull() {
            addCriterion("codigoinvima is null");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaIsNotNull() {
            addCriterion("codigoinvima is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaEqualTo(String value) {
            addCriterion("codigoinvima =", value, "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaNotEqualTo(String value) {
            addCriterion("codigoinvima <>", value, "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaGreaterThan(String value) {
            addCriterion("codigoinvima >", value, "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaGreaterThanOrEqualTo(String value) {
            addCriterion("codigoinvima >=", value, "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaLessThan(String value) {
            addCriterion("codigoinvima <", value, "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaLessThanOrEqualTo(String value) {
            addCriterion("codigoinvima <=", value, "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaLike(String value) {
            addCriterion("codigoinvima like", value, "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaNotLike(String value) {
            addCriterion("codigoinvima not like", value, "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaIn(List<String> values) {
            addCriterion("codigoinvima in", values, "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaNotIn(List<String> values) {
            addCriterion("codigoinvima not in", values, "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaBetween(String value1, String value2) {
            addCriterion("codigoinvima between", value1, value2, "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaNotBetween(String value1, String value2) {
            addCriterion("codigoinvima not between", value1, value2, "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("estado is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("estado is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(BigDecimal value) {
            addCriterion("estado =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(BigDecimal value) {
            addCriterion("estado <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(BigDecimal value) {
            addCriterion("estado >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("estado >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(BigDecimal value) {
            addCriterion("estado <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("estado <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<BigDecimal> values) {
            addCriterion("estado in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<BigDecimal> values) {
            addCriterion("estado not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("estado between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("estado not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andNombreIsNull() {
            addCriterion("nombre is null");
            return (Criteria) this;
        }

        public Criteria andNombreIsNotNull() {
            addCriterion("nombre is not null");
            return (Criteria) this;
        }

        public Criteria andNombreEqualTo(String value) {
            addCriterion("nombre =", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotEqualTo(String value) {
            addCriterion("nombre <>", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThan(String value) {
            addCriterion("nombre >", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThanOrEqualTo(String value) {
            addCriterion("nombre >=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThan(String value) {
            addCriterion("nombre <", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThanOrEqualTo(String value) {
            addCriterion("nombre <=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLike(String value) {
            addCriterion("nombre like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotLike(String value) {
            addCriterion("nombre not like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreIn(List<String> values) {
            addCriterion("nombre in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotIn(List<String> values) {
            addCriterion("nombre not in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreBetween(String value1, String value2) {
            addCriterion("nombre between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotBetween(String value1, String value2) {
            addCriterion("nombre not between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andCodigoinvimaLikeInsensitive(String value) {
            addCriterion("upper(codigoinvima) like", value.toUpperCase(), "codigoinvima");
            return (Criteria) this;
        }

        public Criteria andNombreLikeInsensitive(String value) {
            addCriterion("upper(nombre) like", value.toUpperCase(), "nombre");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usc.registrossanitarios
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}