package co.edu.usc.interacciones.dao.model;

import co.edu.usc.interacciones.dao.model.RegistroFabric;
import co.edu.usc.interacciones.dao.model.RegistroFabricExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegistroFabricMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    int countByExample(RegistroFabricExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    int deleteByExample(RegistroFabricExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    int insert(RegistroFabric record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    int insertSelective(RegistroFabric record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    List<RegistroFabric> selectByExample(RegistroFabricExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RegistroFabric record, @Param("example") RegistroFabricExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RegistroFabric record, @Param("example") RegistroFabricExample example);
}