package co.edu.usc.interacciones.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RegistroFabricExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    public RegistroFabricExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFabricImportIdfabricImportIsNull() {
            addCriterion("fabric_import_idfabric_import is null");
            return (Criteria) this;
        }

        public Criteria andFabricImportIdfabricImportIsNotNull() {
            addCriterion("fabric_import_idfabric_import is not null");
            return (Criteria) this;
        }

        public Criteria andFabricImportIdfabricImportEqualTo(BigDecimal value) {
            addCriterion("fabric_import_idfabric_import =", value, "fabricImportIdfabricImport");
            return (Criteria) this;
        }

        public Criteria andFabricImportIdfabricImportNotEqualTo(BigDecimal value) {
            addCriterion("fabric_import_idfabric_import <>", value, "fabricImportIdfabricImport");
            return (Criteria) this;
        }

        public Criteria andFabricImportIdfabricImportGreaterThan(BigDecimal value) {
            addCriterion("fabric_import_idfabric_import >", value, "fabricImportIdfabricImport");
            return (Criteria) this;
        }

        public Criteria andFabricImportIdfabricImportGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fabric_import_idfabric_import >=", value, "fabricImportIdfabricImport");
            return (Criteria) this;
        }

        public Criteria andFabricImportIdfabricImportLessThan(BigDecimal value) {
            addCriterion("fabric_import_idfabric_import <", value, "fabricImportIdfabricImport");
            return (Criteria) this;
        }

        public Criteria andFabricImportIdfabricImportLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fabric_import_idfabric_import <=", value, "fabricImportIdfabricImport");
            return (Criteria) this;
        }

        public Criteria andFabricImportIdfabricImportIn(List<BigDecimal> values) {
            addCriterion("fabric_import_idfabric_import in", values, "fabricImportIdfabricImport");
            return (Criteria) this;
        }

        public Criteria andFabricImportIdfabricImportNotIn(List<BigDecimal> values) {
            addCriterion("fabric_import_idfabric_import not in", values, "fabricImportIdfabricImport");
            return (Criteria) this;
        }

        public Criteria andFabricImportIdfabricImportBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fabric_import_idfabric_import between", value1, value2, "fabricImportIdfabricImport");
            return (Criteria) this;
        }

        public Criteria andFabricImportIdfabricImportNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fabric_import_idfabric_import not between", value1, value2, "fabricImportIdfabricImport");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaIsNull() {
            addCriterion("registrossanitarios_codigoinvima is null");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaIsNotNull() {
            addCriterion("registrossanitarios_codigoinvima is not null");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaEqualTo(String value) {
            addCriterion("registrossanitarios_codigoinvima =", value, "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaNotEqualTo(String value) {
            addCriterion("registrossanitarios_codigoinvima <>", value, "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaGreaterThan(String value) {
            addCriterion("registrossanitarios_codigoinvima >", value, "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaGreaterThanOrEqualTo(String value) {
            addCriterion("registrossanitarios_codigoinvima >=", value, "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaLessThan(String value) {
            addCriterion("registrossanitarios_codigoinvima <", value, "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaLessThanOrEqualTo(String value) {
            addCriterion("registrossanitarios_codigoinvima <=", value, "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaLike(String value) {
            addCriterion("registrossanitarios_codigoinvima like", value, "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaNotLike(String value) {
            addCriterion("registrossanitarios_codigoinvima not like", value, "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaIn(List<String> values) {
            addCriterion("registrossanitarios_codigoinvima in", values, "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaNotIn(List<String> values) {
            addCriterion("registrossanitarios_codigoinvima not in", values, "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaBetween(String value1, String value2) {
            addCriterion("registrossanitarios_codigoinvima between", value1, value2, "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaNotBetween(String value1, String value2) {
            addCriterion("registrossanitarios_codigoinvima not between", value1, value2, "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }

        public Criteria andRegistrossanitariosCodigoinvimaLikeInsensitive(String value) {
            addCriterion("upper(registrossanitarios_codigoinvima) like", value.toUpperCase(), "registrossanitariosCodigoinvima");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table registro_fabric
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table registro_fabric
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}