package co.edu.usc.interacciones.dao.model;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TargetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.targets
     *
     * @mbggenerated
     */
    int countByExample(TargetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.targets
     *
     * @mbggenerated
     */
    int deleteByExample(TargetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.targets
     *
     * @mbggenerated
     */
    int insert(Targets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.targets
     *
     * @mbggenerated
     */
    int insertSelective(Targets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.targets
     *
     * @mbggenerated
     */
    List<Targets> selectByExample(TargetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.targets
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Targets record, @Param("example") TargetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.targets
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Targets record, @Param("example") TargetsExample example);
}