package co.edu.usc.interacciones.dao.model;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UnidadesmedidaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.unidadesmedida
     *
     * @mbggenerated
     */
    int countByExample(UnidadesmedidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.unidadesmedida
     *
     * @mbggenerated
     */
    int deleteByExample(UnidadesmedidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.unidadesmedida
     *
     * @mbggenerated
     */
    int insert(Unidadesmedida record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.unidadesmedida
     *
     * @mbggenerated
     */
    int insertSelective(Unidadesmedida record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.unidadesmedida
     *
     * @mbggenerated
     */
    List<Unidadesmedida> selectByExample(UnidadesmedidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.unidadesmedida
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Unidadesmedida record, @Param("example") UnidadesmedidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.unidadesmedida
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Unidadesmedida record, @Param("example") UnidadesmedidaExample example);
}